---
- name: create a logical volume for OpenShift EmptyDirs
  lvol:
    vg: '{{ origin_ci_docker_volume_group }}'
    lv: 'openshift-xfs-vol-dir'
    size: '100%FREE'
    state: present

- name: make the OpenShift XFS filesystem
  filesystem:
    dev: '/dev/{{ origin_ci_docker_volume_group }}/openshift-xfs-vol-dir'
    fstype: xfs

- name: create the OpenShift XFS mount point
  file:
    path: /mnt/openshift-xfs-vol-dir
    state: directory

- name: mount the OpenShift XFS filesystem
  mount:
    src: '/dev/{{ origin_ci_docker_volume_group }}/openshift-xfs-vol-dir'
    name: /mnt/openshift-xfs-vol-dir
    state: mounted
    fstype: xfs

- name: make the Origin CI user own the OpenShift XFS mount
  file:
    path: /mnt/openshift-xfs-vol-dir
    owner: '{{ origin_ci_user }}'